version: "3"

services:
  mongodb:
    container_name: "docker_compose_local_golang_mongo_graphql_003"
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    # volumes:
    #   - mongodb-data:/data/db
  # redis:
  #   container_name: "docker_compose_local_social_media_hub_api_redis"
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-data:/data
volumes:
  mongodb-data:
  # redis-data: