#!/usr/bin/env bash

printf "seeding local data mongo data\n"

mongo localDb <<EOF
use localDb

var agents = [
  {
    "agentId": "1a",
    "createdDate": "2021-04-13T18:35:26-07:00",
    "updatedDate": "2021-04-13T18:35:26-07:00",
    "name": "Spencer Strasmore",
    "email": "spencer.strasmore@ballers.com",
    "authorIds": ["1a", "1b"]
  },
  {
    "agentId": "1b",
    "createdDate": "2021-04-13T18:35:26-07:00",
    "updatedDate": "2021-04-13T18:35:26-07:00",
    "name": "Billy Mays",
    "email": "billy.mays@ballers.com",
    "authorIds": ["1c"]
  },
  {
    "agentId": "1c",
    "createdDate": "2021-04-13T18:35:26-07:00",
    "updatedDate": "2021-04-13T18:35:26-07:00",
    "name": "Frank Sinatra",
    "email": "frank.sinatra@ballers.com",
    "authorIds": ["1d"]
  }
];

for (const agent of agents) {
  db.getCollection('agents').deleteMany({ agentId: agent.agentId })
}
db.getCollection('agents').insertMany(agents)

var authors = [
  {
    "authorId": "1a",
    "createdDate": "2021-04-13T18:39:45-07:00",
    "updatedDate": "2021-04-13T18:39:45-07:00",
    "name": "Stephen King",
    "website": "https://www.stephen-king.com",
    "agentId": "1a",
    "bookIds": ["1a", "1c"]
  },
  {
    "authorId": "1b",
    "createdDate": "2021-04-13T18:39:45-07:00",
    "updatedDate": "2021-04-13T18:39:45-07:00",
    "name": "Bobby Bushay",
    "website": "https://www.h2o.com",
    "agentId": "1a",
    "bookIds": ["1b"]
  },
  {
    "authorId": "1c",
    "createdDate": "2021-04-13T18:39:45-07:00",
    "updatedDate": "2021-04-13T18:39:45-07:00",
    "name": "Adam Sandler",
    "website": "https://www.billy-madison.com",
    "agentId": "1b",
    "bookIds": ["1d", "1c"]
  },
  {
    "authorId": "1d",
    "createdDate": "2021-04-13T18:39:45-07:00",
    "updatedDate": "2021-04-13T18:39:45-07:00",
    "name": "William Shatner",
    "website": "https://www.the-enterprise.com",
    "agentId": "1c",
    "bookIds": ["1e", "1f", "1a"]
  }
]

for (const author of authors) {
  db.getCollection('authors').deleteMany({ authorId: author.authorId })
}
db.getCollection('authors').insertMany(authors)

var books = [
  {
    "bookId": "1a",
    "createdDate": "2021-04-13T18:58:20-07:00",
    "updatedDate": "2021-04-13T18:58:20-07:00",
    "title": "It",
    "description": "It is a 1986 horror novel by American author Stephen King. It was his 22nd book and his 17th novel written under his own name. The story follows the experiences of seven children as they are terrorized by an evil entity that exploits the fears of its victims to disguise itself while hunting its prey. 'It' primarily appears in the form of Pennywise the Dancing Clown to attract its preferred prey of young children.",
    "cover": "https://en.wikipedia.org/wiki/It_(novel)#/media/File:It_(Stephen_King_novel_-_cover_art).jpg",
    "authorIds": ["1a", "1d"]
  },
  {
    "bookId": "1b",
    "createdDate": "2021-04-13T18:58:20-07:00",
    "updatedDate": "2021-04-13T18:58:20-07:00",
    "title": "Harry Potter and the Philosopher's Stone",
    "description": "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, he faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg",
    "authorIds": ["1b"]
  },
  {
    "bookId": "1c",
    "createdDate": "2021-04-13T18:58:20-07:00",
    "updatedDate": "2021-04-13T18:58:20-07:00",
    "title": "The Little Prince",
    "description": "The Little Prince (French: Le Petit Prince, pronounced [lə p(ə)ti pʁɛ̃s]) is a novella by French aristocrat, writer, and aviator Antoine de Saint-Exupéry. It was first published in English and French in the US by Reynal & Hitchcock in April 1943, and posthumously in France following the liberation of France as Saint-Exupéry's works had been banned by the Vichy Regime. The story follows a young prince who visits various planets in space, including Earth, and addresses themes of loneliness, friendship, love, and loss. Despite its style as a children's book, The Little Prince makes observations about life and human nature.[8]",
    "cover": "https://upload.wikimedia.org/wikipedia/en/0/05/Littleprince.JPG",
    "authorIds": ["1a", "1c"]
  },
  {
    "bookId": "1d",
    "createdDate": "2021-04-13T18:58:20-07:00",
    "updatedDate": "2021-04-13T18:58:20-07:00",
    "title": "Dream of Red Chamber",
    "description": "Dream of the Red Chamber, also called The Story of the Stone, or Hongloumeng (simplified Chinese: 红楼梦; traditional Chinese: 紅樓夢; pinyin: Hónglóumèng), composed by Cao Xueqin, is one of China's Four Great Classical Novels. It was written some time in the middle of the 18th century during the Qing dynasty. Long considered a masterpiece of Chinese literature, the novel is generally acknowledged to be one of the pinnacles of Chinese fiction.[1] 'Redology' is the field of study devoted exclusively to this work.[2]",
    "cover": "https://upload.wikimedia.org/wikipedia/commons/7/79/Hongloumeng2.jpg",
    "authorIds": ["1c"]
  },
  {
    "bookId": "1e",
    "createdDate": "2021-04-13T18:58:20-07:00",
    "updatedDate": "2021-04-13T18:58:20-07:00",
    "title": "The Hobbit",
    "description": "The Hobbit is set within Tolkien's fictional universe and follows the quest of home-loving Bilbo Baggins, the titular hobbit, to win a share of the treasure guarded by Smaug the dragon. Bilbo's journey takes him from light-hearted, rural surroundings into more sinister territory.",
    "cover": "https://upload.wikimedia.org/wikipedia/en/4/4a/TheHobbit_FirstEdition.jpg",
    "authorIds": ["1d"]
  },
  {
    "bookId": "1f",
    "createdDate": "2021-04-13T18:58:20-07:00",
    "updatedDate": "2021-04-13T18:58:20-07:00",
    "title": "An Then There Were None",
    "description": "And Then There Were None is a mystery novel by the English writer Agatha Christie, described by her as the most difficult of her books to write.[2] It was first published in the United Kingdom by the Collins Crime Club on 6 November 1939, as Ten Little Niggers,[3] after the children's counting rhyme and minstrel song, which serves as a major element of the plot.[4][5] A US edition was released in January 1940 with the title And Then There Were None, which is taken from the last five words of the song.[6] All successive American reprints and adaptations use that title, except for the Pocket Books paperbacks published between 1964 and 1986, which appeared under the title Ten Little Indians.",
    "cover": "https://images-na.ssl-images-amazon.com/images/I/51ToJjGoTcL._SX325_BO1,204,203,200_.jpg",
    "authorIds": ["1d"]
  }
]

for (const book of books) {
  db.getCollection('books').deleteMany({ bookId: book.bookId })
}
db.getCollection('books').insertMany(books)

quit()
EOF

printf "seeded local data mongo data\n"